name: MkDocs Site Deployment
on:
  push:
    branches:
      - 'main'
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip install -r requirements.txt
      # Builds doc site, commits changes, and pushes to `gh-pages` branch
      - run: mkdocs gh-deploy --force
