name: MkDocs Site Deployment
on:
  push:
    branches:
      - 'main'
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: sudo pip install -r requirements.txt
      - run: |
        cd docs/stylesheets/icons/
        ln -s /usr/local/lib/python3.1*/dist-packages/material/.icons/*/ .
        cd
      # Builds doc site, commits changes, and pushes to `gh-pages` branch
      - run: mkdocs gh-deploy --force
